
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param code
     * @return
     *     returns service.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://service/", className = "service.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://service/", className = "service.GetCompteResponse")
    @Action(input = "http://service/BanqueWS/getCompteRequest", output = "http://service/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroToDh", targetNamespace = "http://service/", className = "service.ConversionEuroToDh")
    @ResponseWrapper(localName = "conversionEuroToDhResponse", targetNamespace = "http://service/", className = "service.ConversionEuroToDhResponse")
    @Action(input = "http://service/BanqueWS/conversionEuroToDhRequest", output = "http://service/BanqueWS/conversionEuroToDhResponse")
    public double conversionEuroToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param xTerrain
     * @param widthTerrain
     * @param width
     * @param xball
     * @param yball
     * @param height
     * @return
     *     returns service.Faute
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fauteJ2AvecRebons", targetNamespace = "http://service/", className = "service.FauteJ2AvecRebons")
    @ResponseWrapper(localName = "fauteJ2AvecRebonsResponse", targetNamespace = "http://service/", className = "service.FauteJ2AvecRebonsResponse")
    @Action(input = "http://service/BanqueWS/fauteJ2AvecRebonsRequest", output = "http://service/BanqueWS/fauteJ2AvecRebonsResponse")
    public Faute fauteJ2AvecRebons(
        @WebParam(name = "xball", targetNamespace = "")
        int xball,
        @WebParam(name = "yball", targetNamespace = "")
        int yball,
        @WebParam(name = "width", targetNamespace = "")
        int width,
        @WebParam(name = "height", targetNamespace = "")
        int height,
        @WebParam(name = "widthTerrain", targetNamespace = "")
        int widthTerrain,
        @WebParam(name = "xTerrain", targetNamespace = "")
        int xTerrain);

    /**
     * 
     * @param xTerrain
     * @param widthTerrain
     * @param width
     * @param xball
     * @param yball
     * @param height
     * @return
     *     returns service.Faute
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fauteJ1SansRebons", targetNamespace = "http://service/", className = "service.FauteJ1SansRebons")
    @ResponseWrapper(localName = "fauteJ1SansRebonsResponse", targetNamespace = "http://service/", className = "service.FauteJ1SansRebonsResponse")
    @Action(input = "http://service/BanqueWS/fauteJ1SansRebonsRequest", output = "http://service/BanqueWS/fauteJ1SansRebonsResponse")
    public Faute fauteJ1SansRebons(
        @WebParam(name = "xball", targetNamespace = "")
        int xball,
        @WebParam(name = "yball", targetNamespace = "")
        int yball,
        @WebParam(name = "width", targetNamespace = "")
        int width,
        @WebParam(name = "height", targetNamespace = "")
        int height,
        @WebParam(name = "widthTerrain", targetNamespace = "")
        int widthTerrain,
        @WebParam(name = "xTerrain", targetNamespace = "")
        int xTerrain);

    /**
     * 
     * @param xTerrain
     * @param widthTerrain
     * @param width
     * @param xball
     * @param yball
     * @param height
     * @return
     *     returns service.Faute
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fauteJ1AvecRebons", targetNamespace = "http://service/", className = "service.FauteJ1AvecRebons")
    @ResponseWrapper(localName = "fauteJ1AvecRebonsResponse", targetNamespace = "http://service/", className = "service.FauteJ1AvecRebonsResponse")
    @Action(input = "http://service/BanqueWS/fauteJ1AvecRebonsRequest", output = "http://service/BanqueWS/fauteJ1AvecRebonsResponse")
    public Faute fauteJ1AvecRebons(
        @WebParam(name = "xball", targetNamespace = "")
        int xball,
        @WebParam(name = "yball", targetNamespace = "")
        int yball,
        @WebParam(name = "width", targetNamespace = "")
        int width,
        @WebParam(name = "height", targetNamespace = "")
        int height,
        @WebParam(name = "widthTerrain", targetNamespace = "")
        int widthTerrain,
        @WebParam(name = "xTerrain", targetNamespace = "")
        int xTerrain);

    /**
     * 
     * @param xTerrain
     * @param widthTerrain
     * @param width
     * @param xball
     * @param yball
     * @param height
     * @return
     *     returns service.Faute
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fauteJ2SansRebons", targetNamespace = "http://service/", className = "service.FauteJ2SansRebons")
    @ResponseWrapper(localName = "fauteJ2SansRebonsResponse", targetNamespace = "http://service/", className = "service.FauteJ2SansRebonsResponse")
    @Action(input = "http://service/BanqueWS/fauteJ2SansRebonsRequest", output = "http://service/BanqueWS/fauteJ2SansRebonsResponse")
    public Faute fauteJ2SansRebons(
        @WebParam(name = "xball", targetNamespace = "")
        int xball,
        @WebParam(name = "yball", targetNamespace = "")
        int yball,
        @WebParam(name = "width", targetNamespace = "")
        int width,
        @WebParam(name = "height", targetNamespace = "")
        int height,
        @WebParam(name = "widthTerrain", targetNamespace = "")
        int widthTerrain,
        @WebParam(name = "xTerrain", targetNamespace = "")
        int xTerrain);

    /**
     * 
     * @param xTerrain
     * @param widthTerrain
     * @param width
     * @param xRebons
     * @param xball
     * @param yball
     * @param height
     * @return
     *     returns service.Faute
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fauteJ2AxeY", targetNamespace = "http://service/", className = "service.FauteJ2AxeY")
    @ResponseWrapper(localName = "fauteJ2AxeYResponse", targetNamespace = "http://service/", className = "service.FauteJ2AxeYResponse")
    @Action(input = "http://service/BanqueWS/fauteJ2AxeYRequest", output = "http://service/BanqueWS/fauteJ2AxeYResponse")
    public Faute fauteJ2AxeY(
        @WebParam(name = "xball", targetNamespace = "")
        int xball,
        @WebParam(name = "yball", targetNamespace = "")
        int yball,
        @WebParam(name = "width", targetNamespace = "")
        int width,
        @WebParam(name = "height", targetNamespace = "")
        int height,
        @WebParam(name = "widthTerrain", targetNamespace = "")
        int widthTerrain,
        @WebParam(name = "xTerrain", targetNamespace = "")
        int xTerrain,
        @WebParam(name = "xRebons", targetNamespace = "")
        int xRebons);

    /**
     * 
     * @return
     *     returns java.util.List<service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://service/", className = "service.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://service/", className = "service.GetComptesResponse")
    @Action(input = "http://service/BanqueWS/getComptesRequest", output = "http://service/BanqueWS/getComptesResponse")
    public List<Compte> getComptes();

    /**
     * 
     * @param xTerrain
     * @param widthTerrain
     * @param width
     * @param xRebons
     * @param xball
     * @param yball
     * @param height
     * @return
     *     returns service.Faute
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fauteJ1AxeY", targetNamespace = "http://service/", className = "service.FauteJ1AxeY")
    @ResponseWrapper(localName = "fauteJ1AxeYResponse", targetNamespace = "http://service/", className = "service.FauteJ1AxeYResponse")
    @Action(input = "http://service/BanqueWS/fauteJ1AxeYRequest", output = "http://service/BanqueWS/fauteJ1AxeYResponse")
    public Faute fauteJ1AxeY(
        @WebParam(name = "xball", targetNamespace = "")
        int xball,
        @WebParam(name = "yball", targetNamespace = "")
        int yball,
        @WebParam(name = "width", targetNamespace = "")
        int width,
        @WebParam(name = "height", targetNamespace = "")
        int height,
        @WebParam(name = "widthTerrain", targetNamespace = "")
        int widthTerrain,
        @WebParam(name = "xTerrain", targetNamespace = "")
        int xTerrain,
        @WebParam(name = "xRebons", targetNamespace = "")
        int xRebons);

}
